import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
// import Link from "next/link";

import { api } from "~/utils/api";

<<<<<<< HEAD
export default function Home({}) {
=======
export default function Home() {
<<<<<<< HEAD
>>>>>>> dev
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
=======
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
>>>>>>> 0e127c0 (Cleaned unused imports)

  const user = useUser();

  const { data } = api.post.getAll.useQuery();
  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
          {data?.map((post) => <div key={post.id}>{post.content}</div>)}
        </div>
      </main>
    </>
  );
}
